name: angio
channels:
- conda-forge
dependencies:
- libpng=1.6.32
- libtiff=4.0.8
- matplotlib=2.1.0
- olefile=0.44
- pillow=4.2.1
- py=1.4.34
- pytest=3.2.1
- docutils=0.14=py35_0
- html5lib=0.999999999=py35_0
- imageio=2.2.0=py35_0
- pandas=0.21.0=py35_0
- pandoc=2.0.0.1
- pandocfilters=1.4.1=py35_0
- pip=9.0.1=py35_0
- python=3.5.4=0
- python-dateutil=2.6.1=py35_0
- scikit-image=0.13.0=py35_3
- setuptools=36.6.0=py35_1
- statsmodels=0.8.0=py35_0
- numpy=1.13.3
- scikit-learn=0.19.1
- scipy=0.19.1
